"""initial database schema with all tables

Revision ID: eedaf27feff4
Revises: 
Create Date: 2026-01-22 22:22:18.615864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eedaf27feff4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=100), nullable=False),
    sa.Column('apellido_cliente', sa.String(length=100), nullable=False),
    sa.Column('dni_cuit', sa.String(length=50), nullable=False),
    sa.Column('email_cliente', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=100), nullable=False),
    sa.Column('direccion_cliente', sa.Text(), nullable=False),
    sa.Column('ciudad_cliente', sa.String(length=100), nullable=False),
    sa.Column('codigo_postal', sa.String(length=20), nullable=False),
    sa.Column('provincia_cliente', sa.String(length=20), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('dni_cuit'),
    sa.UniqueConstraint('email_cliente')
    )
    op.create_table('proovedores',
    sa.Column('id_proovedor', sa.Integer(), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=100), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_proovedor')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre_rol')
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('alto_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ancho_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('profundidad_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_producto'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('usuarios',
    sa.Column('id_usuarios', sa.Integer(), nullable=False),
    sa.Column('nombre_us', sa.String(length=50), nullable=False),
    sa.Column('apellido_us', sa.String(length=50), nullable=False),
    sa.Column('email_us', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuarios'),
    sa.UniqueConstraint('email_us')
    )
    op.create_table('favoritos',
    sa.Column('id_favorito', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('fecha_agregado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_favorito')
    )
    op.create_table('imagenes_productos',
    sa.Column('id_imagen', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('url_imagen', sa.Text(), nullable=False),
    sa.Column('imagen_principal', sa.Boolean(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_imagen')
    )
    op.create_table('inventario',
    sa.Column('id_inventario', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('cantidad_stock', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.Column('utlima_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_inventario'),
    sa.UniqueConstraint('id_producto')
    )
    op.create_table('ordenes',
    sa.Column('id_orden', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_usuarios', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_usuarios'], ['usuarios.id_usuarios'], ),
    sa.PrimaryKeyConstraint('id_orden')
    )
    op.create_table('detalles_orden',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_orden', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_orden'], ['ordenes.id_orden'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_table('pagos',
    sa.Column('id_pago', sa.Integer(), nullable=False),
    sa.Column('id_orden', sa.Integer(), nullable=True),
    sa.Column('mp_preference_id', sa.String(length=150), nullable=True),
    sa.Column('mp_payment_id', sa.String(length=150), nullable=True),
    sa.Column('mp_estado', sa.String(length=50), nullable=True),
    sa.Column('mp_tipo_pago', sa.String(length=50), nullable=True),
    sa.Column('monto_cobrado_mp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_orden'], ['ordenes.id_orden'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pago')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    op.drop_table('detalles_orden')
    op.drop_table('ordenes')
    op.drop_table('inventario')
    op.drop_table('imagenes_productos')
    op.drop_table('favoritos')
    op.drop_table('usuarios')
    op.drop_table('productos')
    op.drop_table('roles')
    op.drop_table('proovedores')
    op.drop_table('clientes')
    op.drop_table('categoria')
    # ### end Alembic commands ###
